### ISSUE TITLE
Meower

### ISSUE THREAD

**Issue by NotFenixio** [Steve4Space/Steve4Space#1]
Hey there, I'm josueart from Scratch, just wanted to let you know that a lot of forumers are in a platform called "Meower", at "app.meower.org". You should join, it's so cool!

Also, if you wanna get an invite for the Guild of the Scratch Forumers, tell me your Discord username.

Best regards!

**Comment by Steve4Space** [comment]
I'll join!
My Discord is Steve4Space as well

**Comment by OneShot-Niko** [comment]
> I'll join! My Discord is Steve4Space as well

🎉
